apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sup-chess.fullname" . }}-frontend
  labels:
    {{- include "sup-chess.labels" . | nindent 4 }}
data:
  default.conf: |-
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ @backend;
        }

        location @backend {
            proxy_pass http://{{ include "sup-chess.fullname" . }}-server:{{ .Values.server.service.port }};
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_cache_bypass $http_upgrade;
        }

        error_page   500 502 503 504  /50x.html;

        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

