apiVersion: v1
kind: Service
metadata:
  name: {{ include "sup-chess.fullname" . }}-server
  labels:
    {{- include "sup-chess.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: server
    {{- include "sup-chess.selectorLabels" . | nindent 4 }}
