apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sup-chess.fullname" . }}-server
  labels:
    {{- include "sup-chess.labels" . | nindent 4 }}
data:
  config.yaml: |-
    chess_engine_url_scheme: "http"
    chess_engine_url_host: "{{ include "sup-chess.fullname" . }}-engine"
    chess_engine_url_port: "{{ .Values.engine.service.port }}"
    redis_host: "{{ include "sup-chess.fullname" . }}-redis-master"
    redis_port: "{{ .Values.redis.master.service.port }}"

