version: "3.9"
services:
  chess-frontend:
    build: frontend
    ports:
      - "8000:80"
    volumes:
      - ./frontend/html:/usr/share/nginx/html
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
  chess-server:
    build: gameserver
    ports:
      - "8001:8000"
    volumes:
      - ./gameserver:/app
  chess-engine:
    build: engine
    ports:
      - "8002:8000"
    volumes:
      - ./engine:/app
